% simple_english.pl - File for HW05, T01
% A simple DCG for the a subset of the english language
%
% Author: T. Wilgenbusch, K. Hipkin, T. Fairman, B. Dell


% Simple English grammar
% (thanks to Manuel Ebert)
%----------------------------------------------------
% 1 (15 points): Write a DCG that generates and analyses
% all meaningful sentences using the following words:
%    sharks, goldfishes, hawks, finches,
%    boys,
%    eat, swim, fly, drown.
% "Meaningful" means that
%    - only birds can fly
%    - herbivores don't eat other beings,
%    - fishes and mammals can swim (but not birds)
%    - mammals and birds can be drown (but not fishes)
% i.e. 'sharks fly' should not be generated
% by your grammar.
% Similarly finches are not carnivores,
%
% Hints:
% - Classify the words and use your classes as node labels.
% - Don't bother with Chomsky Normal Form
%   or other fancy things.
% - Mind that drowning and eating can but not necessarily
%   do take an object.
% - use the symbol s as the start symbol of the grammar
%----------------------------------------------------
%P 6

s --> ...

%----------------------------------------------------
% 2 (5 points). On an ancient scroll written in an even more
% ancient language called 'Pthu' the following sentences
% were found:
%
%    Nqblubh Mhboa.
%    Nqrrroah Ukahama Nqblubh. 
%    Nqlhalha Falup.
%    Nqlhalha Ukahama. 
%    Nqlhalha Ukahama Nqflua. 
%    Nqflua Sharabrab. 
%    Nqblubh Falup Nqdwingi.
%    Nqflua Ukahama Nqdwingi.
%    Nqdwingi Falup Nqflua.
%
% Assume the syntactic structure of Pthu is the same
% as it is in english.
% Use the grammar from the previous task to give a english
% translation for every word of the scroll.
%
% Hints: 
% - Instantiate every Pthu word with an english word and
%   check if all the so-translated sentences are meaningful.
% - You may use built-in predicates for list processing.
% - If you don't get a unique solution or no solution
%   at all it might be because your grammar generates
%   a set of sentences different to the intended one.
%   There should be 43 sentences generated by your grammar.
%

%----------------------------------------------------
translation(Nqrrroah, Nqblubh, Nqflua, Nqdwingi,
            Nqlhalha, Ukahama, Mhboa, Sharabrab, Falup) :-
...